services:
  coordinator:
    container_name: coordinator
    build: ./services/coordinator
    environment:
      CONFIG_FILE_PATH: config.json
    depends_on:
      - telegraf
    networks:
      - systems
    volumes:
      - /app/node_modules
      - ./config.json:/app/config.json:delegated,ro
      - ./services/coordinator/:/app:delegated
    ports:
      - 3000:3000
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M

  orders:
    container_name: orders
    build: ./services/orders
    environment:
      SERVICE_NAME: orders
      CONFIG_FILE_PATH: config.json
    depends_on:
      - telegraf
    networks:
      - systems
    volumes:
      - /app/node_modules
      - ./config.json:/app/config.json:delegated
      - ./services/orders/:/app:delegated

  # orders-2:
  #   container_name: orders-2
  #   build: ./services/orders
  #   environment:
  #     SERVICE_NAME: orders-2
  #   depends_on:
  #     - telegraf
  #   networks:
  #     - systems
  #   volumes:
  #     - /app/node_modules
  #     - ./services/orders/:/app:delegated
    # ports:
    #   - '3000:3000'
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.50'
    #       memory: 50M

  # docker-stats-statsd:
  #   build: ./tools/docker-stats-statsd
  #   depends_on:
  #     - telegraf
  #     - coordinator
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #     - systems

  grafana:
    image: grafana/grafana
    ports:
      - '3001:3000'
    depends_on:
      - influxdb
    networks:
      - systems
    volumes:
      - ./volumes/grafana:/var/lib/grafana

  influxdb:
    container_name: influx
    image: influxdb
    networks:
      - systems
    ports:
      - 8086:8086

  telegraf:
    container_name: telegraf
    image: telegraf
    networks:
      - systems
    ports:
      - 8125:8125/udp
      - 8126:8126
    depends_on:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

networks:
  systems:
