services:
  first:
    container_name: first
    build: ./services/first
    environment:
      CONFIG_FILE_PATH: config.json
      SERVICE_NAME: first
    depends_on:
      - telegraf
    networks:
      - systems
    volumes:
      - /app/node_modules
      - ./config.json:/app/config.json
      - ./services/first/:/app:delegated
    ports:
      - 3000:3000
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 500M

  second:
    container_name: second
    build: ./services/second
    environment:
      SERVICE_NAME: second
      CONFIG_FILE_PATH: config.json
    depends_on:
      - telegraf
    networks:
      - systems
    volumes:
      - /app/node_modules
      - ./config.json:/app/config.json:cached
      - ./services/second/:/app:delegated

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    depends_on:
      - influxdb
    networks:
      - systems
    volumes:
      - ./volumes/grafana:/var/lib/grafana

  influxdb:
    container_name: influx
    image: influxdb
    networks:
      - systems
    ports:
      - 8086:8086

  telegraf:
    container_name: telegraf
    image: telegraf
    networks:
      - systems
    ports:
      - 8125:8125/udp
      - 8126:8126
    depends_on:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

networks:
  systems:
